### ISSUE TITLE
TODO.md, kubernetes manifests

### ISSUE THREAD

**Issue by matthewzhaocc** [UAVCAN/nunaweb#17]
seems like implementing Kubernetes support is on the todo, I'm interested in taking the task. a few question before writing implementation.

1. what kind of customization tool is preferred here? helm, Kustomize, Jsonnet etc. (personal preference Kustomize)
2. is there any environment level customization that is preferred? i.e.: service mesh capability with Istio? specific logging/tracing tooling requirement as sidecars?

**Comment by bbworld1** [comment]
I sort of wrote Kubernetes support into the TODO sort of on the spur of the moment without giving too much thought about it. At our current scale it would probably be pretty overkill to deploy on Kubernetes, but it is a nice thing to have (and in the unlikely case that nunaweb suddenly needs to scale massively it would probably come in handy). That being said:

1. I personally don't have any preference; you can ask @clyde-johnston if there's a preferred tool. Either Kustomize or Helm should be fine.
2. Istio is likely overkill for this task, and in terms of tooling for logging and tracing there's no specific requirements. Do what you think is best but try and keep the deployment relatively simple.

**Comment by clyde-johnston** [comment]
I have no preference although I would consider whether this is really needed. More complexity in the environment means more problems (and cost) to deal with. Simpler is better!
