### ISSUE TITLE
Check ePD/GDPR compliance

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/nunaweb#18]
If this site does not collect any user data (including cookies) it should be okay. Otherwise please ensure it complies with ePD/GDPR

**Comment by bbworld1** [comment]
The site collects no user information. The uploaded DSDL namespaces should be the only data processed by the application, so we should be OK on GDPR compliance, although I'd like to go through and double check just to make sure.

**Comment by pavel-kirienko** [comment]
@bbworld1 I suggest closing this one as there seem to be no actions to take for us.
