### ISSUE TITLE
Licence and Privacy notices

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/nunaweb#19]
Please provide statements on the homepage indicated the following:
1. No user information is collected and the types uploaded are not persisted in any long-term caches on any server.
2. The generated code is the sole property of the user. [The legal entity behind Nunaweb] does not claim any copyright to it.

**Comment by pavel-kirienko** [comment]
> [The legal entity behind Nunaweb]

This GitHub org is formally attached to the *UAVCAN Consortium MTÜ*, so that would be the best approximation of the legal entity you are referencing.

**Comment by bbworld1** [comment]
I noticed that minio object lifecycle was unconfigured (meaning it defaults to storing the uploaded data and results until they are manually deleted). I have rectified this in #22 by configuring minio to automatically delete uploaded data and generated results after 30 days.

Legal statements will be added soon.

**Comment by bbworld1** [comment]
![image](https://user-images.githubusercontent.com/35390537/109269018-bfc95100-77c0-11eb-9b14-a70ad48325dc.png)
Something like this might work? @thirtytwobits

**Comment by pavel-kirienko** [comment]
While we're at it, why not update the copyright as well:

> © 2021 UAVCAN Consortium

**Comment by pavel-kirienko** [comment]
@bbworld1 can you please start a pull request with these changes? They seem sensible.

**Comment by bbworld1** [comment]
Will do.
