### ISSUE TITLE
Nunaweb not accepting .zip uploads

### ISSUE THREAD

**Issue by clyde-johnston** [UAVCAN/nunaweb#2]
After selecting a .zip file (e.g [my_project.zip](https://github.com/UAVCAN/nunaweb/files/5921138/my_project.zip))  for upload and clicking the "Submit" button on the [nunaweb page](http://nunaweb.uavcan.org), there is no response from the web application. There is no error in the logs or any files in the "nunaserver/upload" directory.

In contrast, submitting a github repository produces a .zip file for downloading.

**Comment by bbworld1** [comment]
I've figured out why this happens. The test zip you linked is a single namespace (i.e. there's no sub-namespaces); the backend is currently expects each repository/zip to contain one or more sub-namespaces. I will update the backend to support single-namespace uploads as well.

**Comment by bbworld1** [comment]
Fixed by #3 .
