### ISSUE TITLE
Use newer, faster Nunavut

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunaweb#24]
This tool should use a newer version of Nunavut to take advantage of the recent significant performance improvements:

- https://github.com/UAVCAN/nunavut/pull/198
- https://github.com/UAVCAN/nunavut/pull/199

**Comment by bbworld1** [comment]
This actually reminded me that I needed to freeze the pip package versions in requirements.txt to a specific version. This will prevent potential regressions and instability in the future. I've included that change in #29 .

As part of that PR, Nunavut is now locked to 1.2.1, which includes the performance improvements, which should solve the issue.
