### ISSUE TITLE
nginx proxy service gets stuck restarting

### ISSUE THREAD

**Issue by clyde-johnston** [UAVCAN/nunaweb#44]
There are two issues that need to be addressed:

1. The nginx proxy service gets stuck in a restarting state making the website unavailable for users
2. There are no historical logs maintained by the app to determine the cause

The output of docker-compose is:

> CONTAINER ID   IMAGE                          COMMAND                  CREATED       STATUS                          PORTS      NAMES
> 44e20621eba1   uavcan/nunaweb-proxy:latest    "/docker-entrypoint.…"   4 weeks ago   **Restarting (1) 20 seconds ago**              ubuntu_proxy_1
> 4749e46295cc   uavcan/nunaweb-server:latest   "gunicorn '-w 4' '-b…"   4 weeks ago   Up 2 hours (healthy)            8080/tcp   ubuntu_nunaserver_1
> 2f6ae1f37a59   minio/minio:latest             "/usr/bin/docker-ent…"   4 weeks ago   Up 2 hours (healthy)            9000/tcp   ubuntu_minio_1
> e41f0f6e82a6   redis:latest                   "docker-entrypoint.s…"   4 weeks ago   Up 2 hours                      6379/tcp   ubuntu_redis_1
> 009d99955b63   uavcan/nunaweb-server:latest   "celery -A nunaserve…"   4 weeks ago   Up 2 hours                      8080/tcp   ubuntu_celery_1
>

**Comment by songmeo** [comment]
How can I replicate this issue? nunaweb-proxy is working fine. (if it's already fixed, please close it).

**Comment by pavel-kirienko** [comment]
Closing for now; will re-open with more information later if the issue re-appears.
