### ISSUE TITLE
Upgrade key dependencies to the latest versions

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunaweb#49]
The most important ones are:

- [nunavut](https://github.com/OpenCyphal/nunavut)
- MinIO, see https://github.com/OpenCyphal/nunaweb/issues/48
- Celery
- Redis

Nikolas started working on this, but the work could not be completed due to the end of his internship and some other tasks he had to be involved in. His work can be picked up from the `maintenance` branch (or it can be restarted from scratch by borrowing relevant pieces from his branch).

**Comment by songmeo** [comment]
Can I close this ticket?

**Comment by pavel-kirienko** [comment]
Done in https://github.com/OpenCyphal/nunaweb/pull/51
