### ISSUE TITLE
Full(er) list of flags/options?

### ISSUE THREAD

**Issue by bbworld1** [UAVCAN/nunaweb#7]
Right now, we have just a handful of the flags that nunavut actually supports. It may be a good idea to add support for more of them.

On the other hand, nunaweb is designed to be a simple frontend for relative beginners/newcomers, so adding more flags may clutter the UI and make it more confusing.

If there is interest in adding more flags/options, then this is something we can consider. Otherwise, we can leave this issue open for discussion.

**Comment by pavel-kirienko** [comment]
> On the other hand, nunaweb is designed to be a simple frontend for relative beginners/newcomers, so adding more flags may clutter the UI and make it more confusing.

I second this. It was intended as a very simple thing so I suggest we keep it this way at least for now.
