### ISSUE TITLE
Configure continuous deployment from main

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/nunaweb#8]
Clyde, as discussed earlier in Slack, we are going to need this auto-deployed to the k-space server for every push to main.

**Comment by clyde-johnston** [comment]
This task is now complete.  All services have been made into Docker images and are uploaded to Docker Hub on a push to the `main` branch.  The images are then deployed to the production host and restarted.  See [forum](https://forum.uavcan.org/t/an-easy-to-use-web-service-for-compiling-dsdl/1074/44) for details.
